spring:
#  datasource:
#    url: jdbc:mysql://
#    username:
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#  h2:
#    console:
#      enabled: true
#      path: /console
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: pass
  devtools:
    livereload:
      enabled: true
  thymeleaf:
      cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1099004382515-oskbn1el2lrh24vcsn48v6c3lp3f92hb.apps.googleusercontent.com
            client-secret: yv6gXNRNemAbPdUC9dYoXnTP
          facebook:
            client-id: 351931512309187
            client-secret: fd6a20688308ef5d8d3faa105e9f527f
custom:
  oauth2:
    kakao:
      client-id: 1b8ff676ae01724ed77437f98d399543